CREATE TABLE IF NOT EXISTS `ncs_study` (
  `id` int NOT NULL AUTO_INCREMENT,
  `patientId` int NOT NULL,
  `nerveName` varchar(255) NOT NULL,
  `studyType` enum('MOTOR','SENSORY') NOT NULL,
  `distanceMm` double NOT NULL,
  `distalLatencyMs` double NOT NULL,
  `distalAmplitude` double NOT NULL,
  `distalDurationMs` double DEFAULT NULL,
  `proximalLatencyMs` double DEFAULT NULL,
  `proximalAmplitude` double DEFAULT NULL,
  `proximalDurationMs` double DEFAULT NULL,
  `skinTemperatureCelsius` double DEFAULT NULL,
  `conductionVelocityMPerS` double DEFAULT NULL,
  `amplitudeDropPercent` double DEFAULT NULL,
  `temporalDispersionPercent` double DEFAULT NULL,
  `isNormal` tinyint NOT NULL,
  `axonalLoss` tinyint NOT NULL,
  `demyelination` tinyint NOT NULL,
  `conductionBlock` tinyint NOT NULL,
  `diagnosticSummary` text NOT NULL,
  `recordedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `FK_ncs_study_patientId` (`patientId`),
  CONSTRAINT `FK_ncs_study_patientId` FOREIGN KEY (`patientId`) REFERENCES `patient` (`id`) ON DELETE CASCADE,
  CONSTRAINT `CHK_ncs_study_distanceMm` CHECK (`distanceMm` > 0),
  CONSTRAINT `CHK_ncs_study_distalLatencyMs` CHECK (`distalLatencyMs` > 0 AND `distalAmplitude` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
