CREATE TABLE `edss_assesment` (
  `id` int NOT NULL AUTO_INCREMENT,
  `patientId` int NOT NULL,
  `assessedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `pyramidalSystem` int NOT NULL,
  `cerebellarSystem` int NOT NULL,
  `brainstemSystem` int NOT NULL,
  `sensorySystem` int NOT NULL,
  `bowelBladderSystem` int NOT NULL,
  `visualSystem` int NOT NULL,
  `mentalSystem` int NOT NULL,
  `unassistedWalkingDistanceMeters` int DEFAULT NULL,
  `requiresUnilateralAid` tinyint NOT NULL DEFAULT 0,
  `requiresBilateralAid` tinyint NOT NULL DEFAULT 0,
  `wheelchairBound` tinyint NOT NULL DEFAULT 0,
  `totalScore` decimal(3,1) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_edss_assesment_patientId` (`patientId`),
  CONSTRAINT `FK_edss_assesment_patientId` FOREIGN KEY (`patientId`) REFERENCES `patient` (`id`) ON DELETE CASCADE,
  CONSTRAINT `CHK_edss_pyramidalSystem` CHECK (`pyramidalSystem` BETWEEN 0 AND 6),
  CONSTRAINT `CHK_edss_cerebellarSystem` CHECK (`cerebellarSystem` BETWEEN 0 AND 5),
  CONSTRAINT `CHK_edss_brainstemSystem` CHECK (`brainstemSystem` BETWEEN 0 AND 5),
  CONSTRAINT `CHK_edss_sensorySystem` CHECK (`sensorySystem` BETWEEN 0 AND 6),
  CONSTRAINT `CHK_edss_bowelBladderSystem` CHECK (`bowelBladderSystem` BETWEEN 0 AND 6),
  CONSTRAINT `CHK_edss_visualSystem` CHECK (`visualSystem` BETWEEN 0 AND 6),
  CONSTRAINT `CHK_edss_mentalSystem` CHECK (`mentalSystem` BETWEEN 0 AND 5),
  CONSTRAINT `CHK_edss_totalScore` CHECK (`totalScore` BETWEEN 0 AND 10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
